export const DEFAULT_SETTINGS = {
  MEMSMITH_MODEL: 'claude-sonnet-4-6',
  MEMSMITH_CONTEXT_OBSERVATIONS: '50',
  MEMSMITH_WORKER_PORT: '37777',
  MEMSMITH_WORKER_HOST: '127.0.0.1',

  MEMSMITH_PROVIDER: 'claude',
  MEMSMITH_GEMINI_API_KEY: '',
  MEMSMITH_GEMINI_MODEL: 'gemini-2.5-flash-lite',
  MEMSMITH_OPENROUTER_API_KEY: '',
  MEMSMITH_OPENROUTER_MODEL: 'xiaomi/mimo-v2-flash:free',
  MEMSMITH_OPENROUTER_SITE_URL: '',
  MEMSMITH_OPENROUTER_APP_NAME: 'memsmith',
  MEMSMITH_OLLAMA_URL: 'http://localhost:11434/v1',
  MEMSMITH_OLLAMA_MODEL: 'qwen2.5:14b',
  MEMSMITH_GEMINI_RATE_LIMITING_ENABLED: 'true',


  MEMSMITH_CONTEXT_SESSION_COUNT: '10',

} as const;
